id: P629B2652
initial_creation_type: ocr
source_metadata:
  volumes:
    55d6b9854d6645a287f0aab7cd840924:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: ''
      total_pages: 1201
      volume_number: 46
